### ISSUE TITLE
Effet de la case eau

### ISSUE THREAD

**Issue by louisapraszezynki** [louisapraszezynki/POO-TSDM-6#1]
Définir les effets lorsqu'une unité se déplace par une case de type 'eau' : 
- doit enlever un point de mouvement à ceux qu'il lui reste
- s'il ne lui reste déjà pas de point de mouvement : pas d'effet

Fichier `unit.py` : 

```
def move(self, dx, dy, terrain_grid):
        """Déplace l'unité en tenant compte des restrictions du terrain."""
        new_x = self.x + dx
        new_y = self.y + dy

        # Vérifiez que la position cible est dans la grille
        if 0 <= new_x < GRID_SIZE and 0 <= new_y < GRID_SIZE:
            terrain_type = terrain_grid[new_y][new_x]

            # Bloquez le déplacement sur un mur
            if terrain_type == "wall":
                return  # Pas de déplacement si c'est un mur

            # Appliquez des effets selon le type de terrain
            if terrain_type == "fire":
                self.health -= 5  # Le feu inflige des dégâts

            # Rajouter l'effet de la case eau

            # Déplacez l'unité si le terrain est accessible
            self.x = new_x
            self.y = new_y
```

**Comment by jjyutm4532** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the move method to handle water tiles. When a unit moves to a water tile, it loses one movement point if it has any left. If it doesn't have any movement points left, there's no effect.

You can review changes in this commit: https://github.com/jjyutm4532/louisapraszezynki-POO-TSDM-6-1/commit/06bc37bc5855bc1dd7dd0ceed5c5810cefce9fb7.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by fares-23** [comment]
bon courage

**Comment by louisapraszezynki** [comment]
Le personnage perd un point de mouvement pour le reste de la partie s'il marche sur une case eau :          

```
  # L'eau ralentit
            if terrain_type == "water":
                if self.speed > 0:
                    self.speed -= 1
                else:
                    return 
```
